import { ApiResponse } from "@/types/home";

export const mockNews: ApiResponse = {
  code: 200,
  message: "Success",
  responseObject: {
    course: [
      {
        allAccess: true,
        avgRating: 4.5,
        category: {
          id: 1,
          name: "วิชาพื้นฐาน",
        },
        chapterTotal: 1,
        code: "FREE_ENV08",
        continue: {
          chapterId: 0,
          courseId: 1,
          subType: "none",
          targetId: 0,
          type: "none",
        },
        courseImageUrl:
          "https://api.nida-envi-school.com/data/1/course/1/SUpEzzLLMMbYlGCztRClYISt.png",
        coursePrerequisite: "",
        id: 1,
        inSession: false,
        isCertificate: true,
        isHighlight: true,
        isLocked: false,
        isOpenToRegister: true,
        isRegister: false,
        isWishlist: false,
        learningEndDate: "31/12/2025 20:00:00",
        learningStartDate: "10/01/2022 08:09:00",
        name: "การจัดการเมืองยั่งยืนและเมืองอัจฉริยะ",
        progress: -1,
        published: true,
        registerEndDate: "31/12/2025 12:00:00",
        registerStartDate: "10/01/2022 12:12:00",
        reviewCount: 2,
        trainer: {
          bio: "",
          career: "",
          experience: "",
          firstname: "ณพงศ์",
          id: 10,
          lastname: "นพเกตุ",
          name: "ผศ. ดร. ณพงศ์ นพเกตุ ",
          nickname: "",
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/10/scxLJixhIkrBYxtombmyvIzZ.png",
          title: "ผศ. ดร.",
        },
      },
      {
        allAccess: true,
        avgRating: 0,
        category: {
          id: 1,
          name: "วิชาพื้นฐาน",
        },
        chapterTotal: 1,
        code: "FREE_ENV07",
        continue: {
          chapterId: 0,
          courseId: 2,
          subType: "none",
          targetId: 0,
          type: "none",
        },
        courseImageUrl:
          "https://api.nida-envi-school.com/data/1/course/2/yQEMoHBFAQBmtnIYtDfLHCpW.png",
        coursePrerequisite: "",
        id: 2,
        inSession: false,
        isCertificate: false,
        isHighlight: true,
        isLocked: false,
        isOpenToRegister: true,
        isRegister: false,
        isWishlist: false,
        learningEndDate: "31/12/2025 18:24:00",
        learningStartDate: "10/01/2022 20:10:00",
        name: "การผังเมืองและการใช้ประโยชน์ที่ดิน",
        progress: -1,
        published: true,
        registerEndDate: "31/12/2025 12:00:00",
        registerStartDate: "10/01/2022 21:21:00",
        reviewCount: 0,
        trainer: {
          bio: "",
          career: "",
          experience: "",
          firstname: "ณพงศ์",
          id: 10,
          lastname: "นพเกตุ",
          name: "ผศ. ดร. ณพงศ์ นพเกตุ ",
          nickname: "",
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/10/scxLJixhIkrBYxtombmyvIzZ.png",
          title: "ผศ. ดร.",
        },
      },
      {
        allAccess: true,
        avgRating: 4,
        category: {
          id: 1,
          name: "วิชาพื้นฐาน",
        },
        chapterTotal: 1,
        code: "FREE_ENV06",
        continue: {
          chapterId: 0,
          courseId: 3,
          subType: "none",
          targetId: 0,
          type: "none",
        },
        courseImageUrl:
          "https://api.nida-envi-school.com/data/1/course/3/dwJOrCNEJrCxGkmDXhHpmXvU.png",
        coursePrerequisite: "",
        id: 3,
        inSession: false,
        isCertificate: false,
        isHighlight: true,
        isLocked: false,
        isOpenToRegister: true,
        isRegister: false,
        isWishlist: false,
        learningEndDate: "31/12/2025 17:29:00",
        learningStartDate: "10/01/2022 23:06:00",
        name: "การจัดการสิ่งแวดล้อมตามหลักอุตสาหกรรมเชิงนิเวศ",
        progress: -1,
        published: true,
        registerEndDate: "31/12/2025 12:00:00",
        registerStartDate: "10/01/2022 14:30:00",
        reviewCount: 1,
        trainer: {
          bio: "",
          career: "",
          experience: "",
          firstname: "วิสาขา",
          id: 11,
          lastname: "ภู่จินดา",
          name: "ศ. ดร. วิสาขา ภู่จินดา ",
          nickname: "",
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/11/VsqftSwFdvICcfkvObhnnAhB.jpeg",
          title: "ศ. ดร.",
        },
      },
      {
        allAccess: true,
        avgRating: 5,
        category: {
          id: 1,
          name: "วิชาพื้นฐาน",
        },
        chapterTotal: 1,
        code: "FREE_ENV05",
        continue: {
          chapterId: 0,
          courseId: 4,
          subType: "none",
          targetId: 0,
          type: "none",
        },
        courseImageUrl:
          "https://api.nida-envi-school.com/data/1/course/4/ShbzxFIzaHOfOLyUyzJhJkpL.png",
        coursePrerequisite: "",
        id: 4,
        inSession: false,
        isCertificate: false,
        isHighlight: true,
        isLocked: false,
        isOpenToRegister: true,
        isRegister: false,
        isWishlist: false,
        learningEndDate: "31/12/2025 18:30:00",
        learningStartDate: "10/01/2022 21:30:00",
        name: "มาตรฐานการจัดการสิ่งแวดล้อมและความปลอดภัย",
        progress: -1,
        published: true,
        registerEndDate: "31/12/2025 12:00:00",
        registerStartDate: "10/01/2022 15:20:00",
        reviewCount: 2,
        trainer: {
          bio: "",
          career: "",
          experience: "",
          firstname: "จุฑารัตน์",
          id: 12,
          lastname: "ชมพันธุ์",
          name: "รศ. ดร. จุฑารัตน์ ชมพันธุ์ ",
          nickname: "",
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/12/nrItAEMmkOhtrdONDwFaCpgW.jpeg",
          title: "รศ. ดร.",
        },
      },
      {
        allAccess: true,
        avgRating: 0,
        category: {
          id: 1,
          name: "วิชาพื้นฐาน",
        },
        chapterTotal: 1,
        code: "FREE_ENV04",
        continue: {
          chapterId: 0,
          courseId: 5,
          subType: "none",
          targetId: 0,
          type: "none",
        },
        courseImageUrl:
          "https://api.nida-envi-school.com/data/1/course/5/olGXwmCaMSwZyDmUWSRnbqAm.png",
        coursePrerequisite: "",
        id: 5,
        inSession: false,
        isCertificate: false,
        isHighlight: true,
        isLocked: false,
        isOpenToRegister: true,
        isRegister: false,
        isWishlist: false,
        learningEndDate: "31/12/2025 18:00:00",
        learningStartDate: "10/01/2022 08:20:00",
        name: "จริยธรรมและอุดมการณ์สิ่งแวดล้อม",
        progress: -1,
        published: true,
        registerEndDate: "31/12/2025 12:00:00",
        registerStartDate: "10/01/2022 08:19:00",
        reviewCount: 0,
        trainer: {
          bio: "",
          career: "",
          experience: "",
          firstname: "จุฑารัตน์",
          id: 12,
          lastname: "ชมพันธุ์",
          name: "รศ. ดร. จุฑารัตน์ ชมพันธุ์ ",
          nickname: "",
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/12/nrItAEMmkOhtrdONDwFaCpgW.jpeg",
          title: "รศ. ดร.",
        },
      },
      {
        allAccess: true,
        avgRating: 0,
        category: {
          id: 1,
          name: "วิชาพื้นฐาน",
        },
        chapterTotal: 1,
        code: "FREE_ENV03",
        continue: {
          chapterId: 0,
          courseId: 6,
          subType: "none",
          targetId: 0,
          type: "none",
        },
        courseImageUrl:
          "https://api.nida-envi-school.com/data/1/course/6/XTAMwSBjVakXknmFhXcTqFkS.png",
        coursePrerequisite: "",
        id: 6,
        inSession: false,
        isCertificate: false,
        isHighlight: true,
        isLocked: false,
        isOpenToRegister: true,
        isRegister: false,
        isWishlist: false,
        learningEndDate: "31/12/2025 18:29:00",
        learningStartDate: "10/01/2022 18:30:00",
        name: "สิ่งแวดล้อม นิเวศวิทยา และเทคโนโลยีการจัดการ",
        progress: -1,
        published: true,
        registerEndDate: "31/12/2025 12:00:00",
        registerStartDate: "10/01/2022 07:30:00",
        reviewCount: 0,
        trainer: {
          bio: "",
          career: "",
          experience: "",
          firstname: "ธวัชชัย",
          id: 13,
          lastname: "ศุภดิษฐ์",
          name: "ศ. ดร. ธวัชชัย ศุภดิษฐ์ ",
          nickname: "",
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/13/cbgPiwrfZfrSRgOGSCXRmvtK.jpeg",
          title: "ศ. ดร.",
        },
      },
      {
        allAccess: true,
        avgRating: 3,
        category: {
          id: 1,
          name: "วิชาพื้นฐาน",
        },
        chapterTotal: 1,
        code: "FREE_ENV01",
        continue: {
          chapterId: 0,
          courseId: 8,
          subType: "none",
          targetId: 0,
          type: "none",
        },
        courseImageUrl:
          "https://api.nida-envi-school.com/data/1/course/8/LTCTsqRaMnnHinKlljynhyFb.png",
        coursePrerequisite: "",
        id: 8,
        inSession: false,
        isCertificate: false,
        isHighlight: true,
        isLocked: false,
        isOpenToRegister: true,
        isRegister: false,
        isWishlist: false,
        learningEndDate: "31/12/2025 18:29:00",
        learningStartDate: "10/01/2022 07:30:00",
        name: "มนุษย์และสิ่งแวดล้อม",
        progress: -1,
        published: true,
        registerEndDate: "31/12/2025 04:10:00",
        registerStartDate: "10/01/2022 07:20:00",
        reviewCount: 2,
        trainer: {
          bio: "",
          career: "",
          experience: "",
          firstname: "ภัคพงศ์",
          id: 15,
          lastname: "พจนารถ",
          name: "รศ. ดร. ภัคพงศ์ พจนารถ ",
          nickname: "",
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/15/wXxaQdKTIiYnoOWkfBDobged.jpeg",
          title: "รศ. ดร.",
        },
      },
      {
        allAccess: true,
        avgRating: 0,
        category: {
          id: 1,
          name: "วิชาพื้นฐาน",
        },
        chapterTotal: 1,
        code: "001",
        continue: {
          chapterId: 0,
          courseId: 9,
          subType: "none",
          targetId: 0,
          type: "none",
        },
        courseImageUrl:
          "https://api.nida-envi-school.com/data/template/e-learning.png",
        coursePrerequisite: "",
        id: 9,
        inSession: false,
        isCertificate: true,
        isHighlight: true,
        isLocked: false,
        isOpenToRegister: false,
        isRegister: false,
        isWishlist: false,
        learningEndDate: "31/08/2024 13:36:00",
        learningStartDate: "01/01/2024 02:30:00",
        name: "ทดสอบการเรียน",
        progress: -1,
        published: true,
        registerEndDate: "31/01/2024 00:01:00",
        registerStartDate: "01/01/2024 18:19:00",
        reviewCount: 0,
        trainer: {
          bio: "",
          career: "",
          experience: "",
          firstname: "จุฑารัตน์",
          id: 12,
          lastname: "ชมพันธุ์",
          name: "รศ. ดร. จุฑารัตน์ ชมพันธุ์ ",
          nickname: "",
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/12/nrItAEMmkOhtrdONDwFaCpgW.jpeg",
          title: "รศ. ดร.",
        },
      },
    ],
    forum: [
      {
        allAccess: true,
        canDelete: false,
        canEdit: false,
        canShare: false,
        comments: 1,
        createBy: {
          birthDate: "1970/01/01",
          branch: {
            id: 0,
            name: "ไม่ระบุ",
          },
          cardId: "",
          code: "",
          department: {
            id: 0,
            name: "ไม่ระบุ",
          },
          employeeCode: "",
          firstname: "ชลทิพย์",
          gender: "ไม่ระบุ",
          hasBranch: false,
          id: 17,
          isLogin: true,
          jobAttent: "1970/01/01",
          jobType: {
            id: 0,
            name: "ไม่ระบุ",
          },
          lastname: "เขมรัตน์อำพร",
          name: "ชลทิพย์ เขมรัตน์อำพร ",
          nickname: "",
          position: {
            id: 0,
            name: "ไม่ระบุ",
          },
          positions: [
            {
              department: {
                id: 1,
                name: "DEFAULT",
              },
              id: 1,
              name: "บุคคลทั่วไป",
              total: 44,
            },
          ],
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/17/xPnKqvKVMRrsIoiBaTTMjGOm.jpeg",
          registerDate: "11/01/2022 10:42:48",
          status: "Active",
          tel: "0970535392",
          title: "นางสาว",
          username: "chonlathip+1@wisdomvast.com",
        },
        createDate: "",
        createTime: "3Y",
        detail: "ข้อสอบก่อนเรียน กำหนดผ่านที่กี่%คะ",
        id: 16,
        images: [],
        isLiked: false,
        likes: 2,
        positions: [],
        published: true,
        replies: [
          {
            answer: "สอบถามอาจารย์มาแล้ว  0 % นะคะ",
            createDate: "",
            createTime: "3Y",
            id: 18,
            image: "",
            reply: [
              {
                answer: "อยากรู้เหมือนกัน ขอบคุณค่ะ ^_^",
                createDate: "",
                createTime: "3Y",
                id: 19,
                image: "",
                reply: [],
                totalReply: 0,
                updateDate: "",
                updateTime: "3Y",
                userReply: {
                  birthDate: "",
                  branch: {
                    id: 0,
                    name: "ไม่ระบุ",
                  },
                  cardId: "",
                  code: "",
                  department: {
                    id: 0,
                    name: "ไม่ระบุ",
                  },
                  employeeCode: "",
                  firstname: "นัทธมน",
                  gender: "ไม่ระบุ",
                  hasBranch: false,
                  id: 47,
                  isLogin: true,
                  jobAttent: "",
                  jobType: {
                    id: 0,
                    name: "ไม่ระบุ",
                  },
                  lastname: "ทองสมบูรณ์",
                  name: "นัทธมน ทองสมบูรณ์ ",
                  nickname: "",
                  position: {
                    id: 0,
                    name: "ไม่ระบุ",
                  },
                  positions: [
                    {
                      department: {
                        id: 1,
                        name: "DEFAULT",
                      },
                      id: 1,
                      name: "บุคคลทั่วไป",
                      total: 44,
                    },
                  ],
                  profileImageUrl:
                    "https://api.nida-envi-school.com/data/1/user/47/ShcEGDzeLTjXQvxuFcRYJJcz.jpeg",
                  registerDate: "12/05/2022 16:10:57",
                  status: "Active",
                  tel: "0909090900",
                  title: "นางสาว",
                  username: "luffylove19@gmail.com",
                },
                birthDate: "",
              },
            ],
            totalReply: 1,
            updateDate: "",
            updateTime: "3Y",
            userReply: {
              birthDate: "1970/01/01",
              branch: {
                id: 0,
                name: "ไม่ระบุ",
              },
              cardId: "",
              code: "",
              department: {
                id: 0,
                name: "ไม่ระบุ",
              },
              employeeCode: "qwe122345",
              firstname: "nuttha",
              gender: "หญิง",
              hasBranch: false,
              id: 24,
              isLogin: true,
              jobAttent: "1970/01/01",
              jobType: {
                id: 0,
                name: "ไม่ระบุ",
              },
              lastname: "mooon",
              name: "nuttha mooon ",
              nickname: "",
              position: {
                id: 0,
                name: "ไม่ระบุ",
              },
              positions: [
                {
                  department: {
                    id: 1,
                    name: "DEFAULT",
                  },
                  id: 2,
                  name: "นักศึกษาลงทะเบียน",
                  total: 19,
                },
              ],
              profileImageUrl:
                "https://api.nida-envi-school.com/data/1/user/24/HjrtJYmDlNzENXpeXFOBEmAZ.jpeg",
              registerDate: "18/01/2022 17:30:15",
              status: "Active",
              tel: "0989856236",
              title: "นาย",
              username: "nutthamon+1@wisdomvast.com",
            },
            birthDate: "",
          },
        ],
        shareCount: 0,
        title: "ข้อสอบก่อนเรียน กำหนดผ่านที่กี่%คะ",
        updateDate: "",
        updateTime: "3Y",
        views: 19,
      },
      {
        allAccess: true,
        canDelete: false,
        canEdit: false,
        canShare: false,
        comments: 1,
        createBy: {
          birthDate: "1970/01/01",
          branch: {
            id: 0,
            name: "ไม่ระบุ",
          },
          cardId: "",
          code: "",
          department: {
            id: 0,
            name: "ไม่ระบุ",
          },
          employeeCode: "",
          firstname: "ชลทิพย์",
          gender: "ไม่ระบุ",
          hasBranch: false,
          id: 17,
          isLogin: true,
          jobAttent: "1970/01/01",
          jobType: {
            id: 0,
            name: "ไม่ระบุ",
          },
          lastname: "เขมรัตน์อำพร",
          name: "ชลทิพย์ เขมรัตน์อำพร ",
          nickname: "",
          position: {
            id: 0,
            name: "ไม่ระบุ",
          },
          positions: [
            {
              department: {
                id: 1,
                name: "DEFAULT",
              },
              id: 1,
              name: "บุคคลทั่วไป",
              total: 44,
            },
          ],
          profileImageUrl:
            "https://api.nida-envi-school.com/data/1/user/17/xPnKqvKVMRrsIoiBaTTMjGOm.jpeg",
          registerDate: "11/01/2022 10:42:48",
          status: "Active",
          tel: "0970535392",
          title: "นางสาว",
          username: "chonlathip+1@wisdomvast.com",
        },
        createDate: "",
        createTime: "3Y",
        detail: "สามารถดาวน์โหลดเอกสารการเรียนได้ที่ไหนคะ?",
        id: 17,
        images: [],
        isLiked: false,
        likes: 0,
        positions: [],
        published: true,
        replies: [
          {
            answer: "สามารถดาวน์โหลดได้ที่หน้ารายละเอียดวิชานั้นๆได้เลยค่ะ",
            createDate: "",
            createTime: "3Y",
            id: 20,
            image: "",
            reply: [],
            totalReply: 0,
            updateDate: "",
            updateTime: "3Y",
            userReply: {
              birthDate: "",
              branch: {
                id: 0,
                name: "ไม่ระบุ",
              },
              cardId: "",
              code: "",
              department: {
                id: 0,
                name: "ไม่ระบุ",
              },
              employeeCode: "",
              firstname: "นัทธมน",
              gender: "ไม่ระบุ",
              hasBranch: false,
              id: 47,
              isLogin: true,
              jobAttent: "",
              jobType: {
                id: 0,
                name: "ไม่ระบุ",
              },
              lastname: "ทองสมบูรณ์",
              name: "นัทธมน ทองสมบูรณ์ ",
              nickname: "",
              position: {
                id: 0,
                name: "ไม่ระบุ",
              },
              positions: [
                {
                  department: {
                    id: 1,
                    name: "DEFAULT",
                  },
                  id: 1,
                  name: "บุคคลทั่วไป",
                  total: 44,
                },
              ],
              profileImageUrl:
                "https://api.nida-envi-school.com/data/1/user/47/ShcEGDzeLTjXQvxuFcRYJJcz.jpeg",
              registerDate: "12/05/2022 16:10:57",
              status: "Active",
              tel: "0909090900",
              title: "นางสาว",
              username: "luffylove19@gmail.com",
            },
            birthDate: "",
          },
        ],
        shareCount: 0,
        title: "สามารถดาวน์โหลดเอกสารการเรียนได้ที่ไหนคะ?",
        updateDate: "",
        updateTime: "3Y",
        views: 19,
      },
    ],
    news: [
      {
        allAccess: true,
        attachType: {
          id: 1,
          name: "Single Image",
        },
        canShare: true,
        comments: 2,
        description:
          '"นิด้า" เปิดให้ "นักศึกษาต่างสถาบัน" สามารถลงทะเบียนเรียนรายวิชาที่สนใจที่จัดการเรียนการสอนใน 11 คณะ และ 1 วิทยาลัยของสถาบันฯ ได้ตั้งแต่ภาคการศึกษา 3/2564 เป็นต้นไป\r\n\r\nการประชุมคณะผู้บริหารบัณฑิตศึกษามหาวิทยาลัยของรัฐและมหาวิทยาลัยในกำกับของรัฐ (ทคบร.) เปิดโอกาสให้นักศึกษาต่างมหาวิทยาลัยของรัฐและในกำกับของรัฐ จำนวน 25 แห่ง ลงทะเบียนเรียนข้ามสถาบันได้ "นิด้า" หนึ่งในสถาบันสมาชิก (ทคบร.) เปิดให้นักศึกษาต่างสถาบันสามารถลงทะเบียนเรียนรายวิชาที่สนใจที่จัดการเรียนการสอนใน 11 คณะ และ 1 วิทยาลัยของสถาบันฯ ได้ตั้งแต่ภาคการศึกษา 3/2564 เป็นต้นไป\r\n\r\nทั้งนี้ หลักสูตรปริญญาโท "ภาษาอังกฤษเพื่อการพัฒนาอาชีพ" คณะภาษาและการสื่อสาร เปิดให้นักศึกษาปริญญาโทที่สนใจ สามารถลงทะเบียนเรียนรายวิชา "ภาษาอังกฤษเพื่อการสื่อสารระหว่างวัฒนธรรม" บรรยายโดย อาจารย์ ดร. ภัทราวุธ เจริญรูป ได้ตั้งแต่วันนี้ ทั้งนี้ จะทำการเรียนการสอนในรูปแบบออนไลน์ ระยะเวลา 8 สัปดาห์\r\n\r\nเริ่มเรียนในเดือนมิถุนายน 2565 แบ่งเป็นสองภาค ดังนี้\r\n\r\nภาคปกติ ทุกวันพุธ เวลา 09.00-16.00 น. (เริ่ม 8 มิ.ย. 65)\r\nภาคพิเศษ ทุกวันเสาร์ เวลา 09.00-16.00 น. (เริ่ม 4 มิ.ย.65)\r\n\r\nสอบถามข้อมูลเพิ่มเติมได้ที่ 087-826-8591 (ธาราทิพย์ ชื่นเพ็ง) และ 089-496-4597 (วัชรี สีห์รา) หรือเว็บไซต์ NIDA WISDOM FOR CHANGE และ YouTube : NIDA THAILAND\r\nที่มา : https://www.bangkokbiznews.com/social/1002698 จากข่าวกรุงเทพธุรกิจ',
        duration: "",
        id: 6,
        imageUrl:
          "https://api.nida-envi-school.com/data/1/news/6/CHMdLGGcVetaxBqOfQkyXgpk.png",
        isLiked: false,
        likes: 2,
        positions: [],
        publishDate: "18/05/2022 21:45:12",
        title: '"นิด้า" พลิกโฉมอุดมศึกษาไทย เปิดลงทะเบียนเรียนข้ามสถาบัน',
        topicType: {
          id: 1,
          name: "news",
        },
        total: 2,
        updateDate: "",
        updateTime: "1Y",
        views: 31,
      },
      {
        allAccess: true,
        attachType: {
          id: 3,
          name: "Youtube Link",
        },
        canShare: true,
        comments: 1,
        description: "โครงการ NIDA SMART UNIVERSITY",
        duration: "",
        id: 5,
        imageUrl:
          "https://api.nida-envi-school.com/data/1/news/5/VQYDdpSdTAsRNBeddfVdadee.webp",
        isLiked: false,
        likes: 3,
        positions: [],
        publishDate: "21/01/2022 14:11:15",
        title: "โครงการ NIDA SMART UNIVERSITY",
        topicType: {
          id: 1,
          name: "news",
        },
        total: 1,
        updateDate: "",
        updateTime: "3Y",
        views: 107,
      },
      {
        allAccess: true,
        attachType: {
          id: 3,
          name: "Youtube Link",
        },
        canShare: true,
        comments: 0,
        description: "VTR แนะนำสถาบันบัณฑิตพัฒนบริหารศาสตร์",
        duration: "",
        id: 3,
        imageUrl:
          "https://api.nida-envi-school.com/data/1/news/3/qzGtLXRtObNylsjmLOfmJFYq.webp",
        isLiked: false,
        likes: 1,
        positions: [],
        publishDate: "21/01/2022 14:11:09",
        title: "VTR แนะนำสถาบันบัณฑิตพัฒนบริหารศาสตร์",
        topicType: {
          id: 1,
          name: "news",
        },
        total: 0,
        updateDate: "",
        updateTime: "3Y",
        views: 31,
      },
      {
        allAccess: true,
        attachType: {
          id: 3,
          name: "Youtube Link",
        },
        canShare: true,
        comments: 0,
        description:
          "นวัตกรรมการจัดการสิ่งแวดล้อมเพื่อความยั่งยืน : คณะบริหารการพัฒนาสิ่งแวดล้อม",
        duration: "",
        id: 4,
        imageUrl:
          "https://api.nida-envi-school.com/data/1/news/4/kECIAhmvMVeMsMwvLcSEqizn.webp",
        isLiked: false,
        likes: 1,
        positions: [],
        publishDate: "21/01/2022 14:11:12",
        title:
          "นวัตกรรมการจัดการสิ่งแวดล้อมเพื่อความยั่งยืน คณะบริหารการพัฒนาสิ่งแวดล้อม",
        topicType: {
          id: 1,
          name: "news",
        },
        total: 0,
        updateDate: "",
        updateTime: "3Y",
        views: 11,
      },
    ],
  },
};
